version: '3.7'
services:
  www:
    image: php:apache
    volumes:
      -"./:/var/www/html" #sync project dir with container web dir
    ports:
      - "80:80"
      - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE: appotheke
      - MYSQL_USER: user
      - MYSQL_PASSWORD: password
      - MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST: db
      - PMA_PORT: 3306
